language: node_js
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: Tab6RHRjlgzwRWxyyEll8fVZcd0DOvRq3ERpHBpTaULBSWkfNlbit8X319TJdRZCAXDZOtsuNGE8EFZ5i/kDVvdXcq5XaWT+MAOvW8E4BDyy6ranlK88BuWlotSDqw9CbsXpQbUod1oMGUCE1YGo4OdH0/kIrfWpkdQBmALtuVb+eg4J515tyFwiK0nBPaXicMpRmk10MwP3uRaqJVrSG/BKLTgT9t8WP0KhMIG07SPe+AUbGa8uAHrjY/VQ1868ULV7jQDXFYflHvIzQiRYg0/MsTpsxN2yCL6RyN0dNfd3KG5O6GdW3p8hcBi1eNLy2GHmaDeW5C9XaEriBJ6aS8nEzXbXPJQicEAFqMiYhf/4dbJ14+KO3wV0dRvIIg4qkQw7T1Wd3X2RLXfeheOqgh7nELN5WGo2PSzgAeDSUUM7MrPqDIvFX+vIAHMdtFsr9W8Qj3NYLiop/VoTLyfjOh2gts1xxlXKJhEQuMfc/JXdV7gKPUc6LCTkIWYT/AlnurpZrS1Fc55RCzhQMeCltezI9K2KqlW7/Hzlt9XEIkUVZWDHk8VhanXN0nzrYr5KmOu0Oe48PfsQmWaGZZDUPsVl8hZPbp4y5RrA5i8iOBNwoRALrMAtC3YrokUBLMkH9kv+Ffjoh3Ju/Z5mVWlr3df32EzjKUESd4kbue6vl9E=
