language: node_js
node_js:
  - "lts/carbon"
  - "lts/dubnium"
  - "11"

script:
  - npm run build
  - npm run test:ci

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  skip_cleanup: true
  on:
    tags: true

notifications:
  on_success: change
  on_failure: always
  email: false
  slack:
    secure: Ow3nDoybNlYZQc98XF8kV3Uy48Sd+Pw4fXi+wMCIzUd5yXHyRCdYlzAqusQm94Gfqp6vtOUJMSCx6pNWbtFUL5gcj+gPA1+YE/ZjFrTi3D289iWXXnZb6q1U4K1tTAGsxan8RV8UtUzyomdIE1zPWEDpZjxzWJKlxsSW6m32G+wMJ0jXVO8e4LzohpIdEK1edPg+bMW08OtHY7d1rhAmNEp9UKDetcY8nn1frqHGlm5WwiNK0rP5MVnMLzS1onOLq+XyuV8M99LpSsavdGcdZ4fzPoC3dYVD+KRhFui2g4wjt2In/F23BD6WyWCRsJKp/tjZ9vXym8M8t1FzyGg3VzOdu0cKseoFlm2rOwxZ06pgJCgANk1Pd+HY2DEscr4gj4lPBP7vxeHvidPrCDrwLA8A8op6NH/9PjJlAvQEdCaklpvePf8n6VOcgbaRMd4e8bQXJxQrKIe/0CFcHyIXa3nqW3Js9GP1WvZZL2DBhQVWcREohWt2g9g6vRqPnVajCUFFbNCckCp/U2di4xkVaiWnEd2J4YitSiXNBQ5E8m1Q0lxAZ1Gl26EeNP2xfqzDdDcwEd2lnrkRKE62bwIF2x5Tl1ifxIgVLqIrRCXhlQiCLXFHtJHYX+8XFVo0U2nKVXq9tMTx4zWD2U812nSt1ZWqMzisOCX7cPXbGuGjLQY=
