language: node_js
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: XY7PcZmERqTuy/Ya5wAceQBTJQFJgB9WuSNwm17TgsvrUNlhOjzBrhp6EwfkMtnnCEdsWRjjjbWZzfawZiu/mW65/zthbDNOaYnWDxMoaBStTnnfNWlFEgc49OON9dZMCe5ZpG7UZO/Db1jMae7ip6J2PM3IkK6BweWT/lum0yG7ift1cabRQ7BnLbS/S6tHOLi1X61hrcIckfKCWc2+lwZ+mEbCuYQmAPBU+aNkK0ouqHw7ifDk9R8UnjCi8m5pAduP45kVMk3mDfH8cy+/EMOyEhuu6Aci16XaPlrbxLfLhcApI4hExlx86loe3rhrgczGOGsbxDAepEp/yCARiVMGF58+3WaYXLZGOLIormJwcR7N8fuAH9EfGfjbIVFMmD4frc4LZwxbpivXjOy1TW8warPvCJzWLZ/oguDIMrU5z5xvGMDtwV8KlVV2GGROF0s/zTI4TrWewavQJ2LRSQQEkrM/5eWx5V6zfwrlTdvmchCbz2AAZyxsY9HFu3qtI4H77R2A9vx+IPd1ydca2eTUd8Qw+li3TILk/pJ67p3Ac5Sr74U19l8v1c88r+3FT0RpPjRBlWLjfd/vCXsdmPfvGvxKnw/sXEo+RgZd8lOoHu3KNKCPRMo9Kg7SaAtUOAHZ6LlChLk1bz8yVXmu1x+0Vf0WZ8tX0D5v97+ct1w=
